version: '3'
services:
  app:
    image: openjdk:11
    container_name: location-service
    ports:
      - 8080:8080
    networks:
      operationseg:
       ipv4_address: 172.25.0.2
    tty: true
    volumes:
      - ./api-location-spring:/location-service:cached
    working_dir: /location-service

  db:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mylocation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mylocationdb
      MYSQL_USER: location
      MYSQL_PASSWORD: location
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./api-location-mysql/mysql/data:/var/lib/mysql
    - ./api-location-mysql/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./api-location-mysql/mysql/db:/docker-entrypoint-initdb.d
    networks:
      operationseg: 
        ipv4_address: 172.25.0.3
    ports:
    - 3306:3306
networks:
  operationseg:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

